"""delete flag

Revision ID: 05ae8cf96067
Revises: df99ed8993ab
Create Date: 2020-01-27 19:37:30.957754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ae8cf96067'
down_revision = 'df99ed8993ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packaging_unit_type', sa.Column('delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packaging_unit_type', 'delete')
    # ### end Alembic commands ###
