"""added purchase columns for user

Revision ID: 115858d5323c
Revises: 8ada85e548bd
Create Date: 2020-01-19 15:09:16.892100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115858d5323c'
down_revision = '8ada85e548bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('beer_demand', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('mixed_demand', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('water_demand', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'water_demand')
    op.drop_column('user', 'mixed_demand')
    op.drop_column('user', 'beer_demand')
    # ### end Alembic commands ###
