"""added otp_secret

Revision ID: 1c73a5aac2bf
Revises: 54ddfc8c4296
Create Date: 2022-07-07 17:19:08.019417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c73a5aac2bf'
down_revision = '54ddfc8c4296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_secret', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    # ### end Alembic commands ###
