"""correct spelling in festival cloumns

Revision ID: 54ddfc8c4296
Revises: a3de5b9faee2
Create Date: 2020-12-20 15:08:24.159173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ddfc8c4296'
down_revision = 'a3de5b9faee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # step 1: create new column
    op.add_column('festival', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('festival', sa.Column('start_date', sa.Date(), nullable=True))

    # step 2: set values
    op.execute('update festival set end_date = enddate')
    op.execute('update festival set start_date = startdate')

    # step 3: set nullable False
    op.alter_column('festival', 'end_date', nullable=False)
    op.alter_column('festival', 'start_date', nullable=False)

    # step 4: drop old column
    op.drop_column('festival', 'startdate')
    op.drop_column('festival', 'enddate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # step 1: create new column
    op.add_column('festival', sa.Column('enddate', sa.Date(), nullable=True))
    op.add_column('festival', sa.Column('startdate', sa.Date(), nullable=True))

    # step 2: set values
    op.execute('update festival set enddate = end_date')
    op.execute('update festival set startdate = start_date')

    # step 3: set nullable False
    op.alter_column('festival', 'enddate', nullable=False)
    op.alter_column('festival', 'startdate', nullable=False)

    # step 4: drop old column
    op.drop_column('festival', 'start_date')
    op.drop_column('festival', 'end_date')

    # ### end Alembic commands ###
