"""added info to item table

Revision ID: 5b85eb5e9680
Revises: 6a6f4e2b3747
Create Date: 2020-01-27 18:48:29.692990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b85eb5e9680'
down_revision = '6a6f4e2b3747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_item', sa.Column('info', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumption_item', 'info')
    # ### end Alembic commands ###
