"""increased info length fo CI

Revision ID: 670e283b7bae
Revises: aba0f523f8b4
Create Date: 2022-08-13 16:58:27.099547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670e283b7bae'
down_revision = 'aba0f523f8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumption_item', 'info',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumption_item', 'info',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
