"""added pku table

Revision ID: 6a6f4e2b3747
Revises: d5fb26062a01
Create Date: 2020-01-20 22:21:47.800645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6f4e2b3747'
down_revision = 'd5fb26062a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_unit_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_unit_type_name'), 'packaging_unit_type', ['name'], unique=False)
    op.add_column('consumption_item', sa.Column('pku_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consumption_item', 'packaging_unit_type', ['pku_id'], ['id'])
    op.drop_column('consumption_item', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_item', sa.Column('unit', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consumption_item', type_='foreignkey')
    op.drop_column('consumption_item', 'pku_id')
    op.drop_index(op.f('ix_packaging_unit_type_name'), table_name='packaging_unit_type')
    op.drop_table('packaging_unit_type')
    # ### end Alembic commands ###
