"""changed post body type

Revision ID: 7a8fe4d5b103
Revises: d029941550a1
Create Date: 2020-03-05 20:00:51.904878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8fe4d5b103'
down_revision = 'd029941550a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=666),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=666),
               nullable=True)
    # ### end Alembic commands ###
