"""festival start and end

Revision ID: 8ada85e548bd
Revises: 713262c80be2
Create Date: 2020-01-19 10:17:28.606873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ada85e548bd'
down_revision = '713262c80be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('festival', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('festival', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('festival', 'start_date')
    op.drop_column('festival', 'end_date')
    # ### end Alembic commands ###
