"""replies

Revision ID: 95f036730aa2
Revises: f74a5b9e8c00
Create Date: 2020-03-07 13:19:38.578085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f036730aa2'
down_revision = 'f74a5b9e8c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'parent_id')
    # ### end Alembic commands ###
