"""chronicle entries

Revision ID: a3de5b9faee2
Revises: 0555e3d69421
Create Date: 2020-06-14 18:31:30.567783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3de5b9faee2'
down_revision = '0555e3d69421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronicle_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('chronicler_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('internal_time', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chronicler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicle_entry_internal_time'), 'chronicle_entry', ['internal_time'], unique=False)
    op.create_index(op.f('ix_chronicle_entry_timestamp'), 'chronicle_entry', ['timestamp'], unique=False)
    op.create_table('chroniclers',
    sa.Column('chronicler_id', sa.Integer(), nullable=True),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chronicler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chroniclers')
    op.drop_index(op.f('ix_chronicle_entry_timestamp'), table_name='chronicle_entry')
    op.drop_index(op.f('ix_chronicle_entry_internal_time'), table_name='chronicle_entry')
    op.drop_table('chronicle_entry')
    # ### end Alembic commands ###
