"""added foreign key to consumptionItem

Revision ID: aba0f523f8b4
Revises: 1c73a5aac2bf
Create Date: 2022-08-12 18:11:52.114729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba0f523f8b4'
down_revision = '1c73a5aac2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_item', sa.Column('festival_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consumption_item', 'festival', ['festival_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consumption_item', type_='foreignkey')
    op.drop_column('consumption_item', 'festival_id')
    # ### end Alembic commands ###
