"""added internal timestamp

Revision ID: db352bbbda17
Revises: 95f036730aa2
Create Date: 2020-03-08 19:58:06.392084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db352bbbda17'
down_revision = '95f036730aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('internal_time', sa.DateTime(), nullable=True))
    op.execute("UPDATE post SET internal_time = timestamp")
    op.create_index(op.f('ix_post_internal_time'), 'post', ['internal_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_internal_time'), table_name='post')
    op.drop_column('post', 'internal_time')
    # ### end Alembic commands ###
