"""added internal name for pku

Revision ID: df99ed8993ab
Revises: 5b85eb5e9680
Create Date: 2020-01-27 19:00:01.931403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df99ed8993ab'
down_revision = '5b85eb5e9680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packaging_unit_type', sa.Column('internal_name', sa.String(length=30), nullable=False))
    op.alter_column('packaging_unit_type', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_packaging_unit_type_internal_name'), 'packaging_unit_type', ['internal_name'], unique=False)
    op.drop_index('ix_packaging_unit_type_name', table_name='packaging_unit_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_packaging_unit_type_name', 'packaging_unit_type', ['name'], unique=False)
    op.drop_index(op.f('ix_packaging_unit_type_internal_name'), table_name='packaging_unit_type')
    op.alter_column('packaging_unit_type', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('packaging_unit_type', 'internal_name')
    # ### end Alembic commands ###
