"""longer descriptions

Revision ID: f74a5b9e8c00
Revises: 7a8fe4d5b103
Create Date: 2020-03-06 17:29:05.710260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74a5b9e8c00'
down_revision = '7a8fe4d5b103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('festival', 'info',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=666),
               existing_nullable=True)
    op.alter_column('user', 'about_me',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=666),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'about_me',
               existing_type=sa.String(length=666),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    op.alter_column('festival', 'info',
               existing_type=sa.String(length=666),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
